### PR TITLE
Dev to master

### PR DESCRIPTION
**Pull request by tunniclm**

### CODE REVIEW

**Comment by tunniclm** [comment]
@ibm-developer looks like master and development got out-of-sync and that master needs to be merged into development before this PR can be merged,

**Comment by mikerott** [comment]
Looks like @ebullient's [PR](https://github.com/ibm-developer/generator-ibm-service-enablement/pull/84) skipped the development branch.  Someone needs to create a PR _from development into master_ to resolve this.  I'll do it.

**Comment by mikerott** [comment]
Actually no I won't.  I don't have sufficient repo permissions.

**Comment by mikerott** [comment]
Actually I do have permissions.  `development` branch is healthy and in sync again with `master`.  This PR build has been automatically restarted.

**Pull request merged**
