### PR TITLE
fix: Updata Watson Conversation Java dependency version to 5.5.0

### PR DESCRIPTION
**Pull request by paulben**

### CODE REVIEW

**Comment by jkingoliver** [comment]
@paulben the name `conversation` was changed to something else recently. Do you think that needs to be updated here as well?

**Comment by paulben** [comment]
@jkingoliver conversation is the only Watson service atm that has a Java binding. If the conversation service is not used any longer should we delete it?

**Comment by Aerex** [comment]
@paulben  Refactoring that service to called `assistant` would mean the change would be a breaking change. Would you want to do that in another PR? I don't see why not doing this. Also, keep in mind the keys that are produced by [Service Registry](https://staging.devex.bluemix.net/registry/)

**Comment by paulben** [comment]
Per Mike Kistler: "Either one should work, but `assistant` is the strategic direction. The intent is that currently they are interchangeable."

So...changing artifactId to `assistant`. 

And if service-watson-conversation gets called for assistant then no need to change that.

**Pull request merged**
